channels:
- anaconda
- conda-forge
- pyviz
dependencies:
- python=3
- pandas
- matplotlib
- notebook
- xlrd
- bokeh
- holoviews
- jupyter_contrib_nbextensions
- scipy
- nbconvert
- hvplot
- scikit-learn
- tqdm
- fiona
- shapely
- six
- descartes
- pysal
- geopy
- pyproj
- geopandas
- scikit-learn
- seaborn
- pymongo
- nltk